version: '3.7'
services:
  test-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - '.:/usr/src/app'
    ports:
    - 5003:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@test-db:5432/test_dev

    depends_on:
      - test-db

  test-db:
    build:
      context: app/api/trial_user_api/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres



